"""add lesson description

Revision ID: 2df53c31c9a2
Revises: d38f0345fe39
Create Date: 2026-05-22 00:29:10.387678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df53c31c9a2'
down_revision: Union[str, Sequence[str], None] = 'd38f0345fe39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'description')
    # ### end Alembic commands ###
